# Generated by Django 5.2.10 on 2026-03-11 11:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Название')),
                ('iso_code', models.CharField(max_length=2, unique=True, verbose_name='ISO Alpha-2')),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('population', models.BigIntegerField(blank=True, null=True)),
                ('flag_emoji', models.CharField(blank=True, max_length=10)),
                ('latest_metrics', models.JSONField(blank=True, default=dict, verbose_name='Актуальные метрики')),
            ],
            options={
                'verbose_name': 'Страна',
                'verbose_name_plural': 'Страны',
            },
        ),
        migrations.CreateModel(
            name='IndicatorCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('slug', models.SlugField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='ViewMode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('slug', models.SlugField(unique=True)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(blank=True)),
                ('population', models.BigIntegerField(blank=True, null=True)),
                ('is_capital', models.BooleanField(default=False)),
                ('latest_metrics', models.JSONField(blank=True, default=dict)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cities', to='main.country')),
            ],
            options={
                'verbose_name': 'Город',
                'verbose_name_plural': 'Города',
                'unique_together': {('name', 'country')},
            },
        ),
        migrations.CreateModel(
            name='Indicator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='Например: cost_of_living, safety_index', max_length=50, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('unit', models.CharField(blank=True, max_length=30)),
                ('higher_better', models.BooleanField(default=True, verbose_name='Выше — лучше?')),
                ('global_min', models.FloatField(blank=True, help_text='Глобальный минимум для нормализации', null=True)),
                ('global_max', models.FloatField(blank=True, help_text='Глобальный максимум', null=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='indicators', to='main.indicatorcategory')),
            ],
        ),
        migrations.CreateModel(
            name='TextInsight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pros', models.JSONField(default=list, help_text='Список плюсов')),
                ('cons', models.JSONField(default=list, help_text='Список минусов')),
                ('summary', models.TextField(help_text='Короткий вывод')),
                ('city', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.city')),
                ('country', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.country')),
                ('mode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.viewmode')),
            ],
        ),
        migrations.CreateModel(
            name='ModeIndicatorWeight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.FloatField(default=1.0)),
                ('indicator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.indicator')),
                ('mode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weights', to='main.viewmode')),
            ],
        ),
        migrations.CreateModel(
            name='DataPoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('value', models.FloatField()),
                ('source', models.CharField(blank=True, max_length=150)),
                ('city', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.city')),
                ('country', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.country')),
                ('indicator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.indicator')),
            ],
            options={
                'indexes': [models.Index(fields=['country', 'year'], name='main_datapo_country_65651c_idx'), models.Index(fields=['city', 'year'], name='main_datapo_city_id_39c324_idx')],
                'unique_together': {('indicator', 'country', 'city', 'year')},
            },
        ),
    ]
