# Generated by Django 5.2.10 on 2026-03-12 09:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='datapoint',
            options={'verbose_name': 'Историческое значение (Точка данных)', 'verbose_name_plural': 'Исторические значения (База данных)'},
        ),
        migrations.AlterModelOptions(
            name='indicator',
            options={'verbose_name': 'Показатель', 'verbose_name_plural': 'Показатели'},
        ),
        migrations.AlterModelOptions(
            name='indicatorcategory',
            options={'verbose_name': 'Категория показателя', 'verbose_name_plural': 'Категории показателей'},
        ),
        migrations.AlterModelOptions(
            name='modeindicatorweight',
            options={'verbose_name': 'Вес показателя', 'verbose_name_plural': 'Веса показателей для режимов'},
        ),
        migrations.AlterModelOptions(
            name='textinsight',
            options={'verbose_name': 'Текстовый инсайт (Вывод)', 'verbose_name_plural': 'Текстовые инсайты (Выводы)'},
        ),
        migrations.AlterModelOptions(
            name='viewmode',
            options={'verbose_name': 'Режим просмотра', 'verbose_name_plural': 'Режимы просмотра'},
        ),
        migrations.AlterField(
            model_name='city',
            name='country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cities', to='main.country', verbose_name='Страна'),
        ),
        migrations.AlterField(
            model_name='city',
            name='is_capital',
            field=models.BooleanField(default=False, verbose_name='Это столица?'),
        ),
        migrations.AlterField(
            model_name='city',
            name='latest_metrics',
            field=models.JSONField(blank=True, default=dict, verbose_name='Актуальные метрики (JSON)'),
        ),
        migrations.AlterField(
            model_name='city',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='city',
            name='population',
            field=models.BigIntegerField(blank=True, null=True, verbose_name='Население'),
        ),
        migrations.AlterField(
            model_name='city',
            name='slug',
            field=models.SlugField(blank=True, verbose_name='URL-адрес (slug)'),
        ),
        migrations.AlterField(
            model_name='country',
            name='flag_emoji',
            field=models.CharField(blank=True, max_length=10, verbose_name='Эмодзи флага'),
        ),
        migrations.AlterField(
            model_name='country',
            name='iso_code',
            field=models.CharField(max_length=2, unique=True, verbose_name='ISO Alpha-2 (Код)'),
        ),
        migrations.AlterField(
            model_name='country',
            name='latest_metrics',
            field=models.JSONField(blank=True, default=dict, verbose_name='Актуальные метрики (JSON)'),
        ),
        migrations.AlterField(
            model_name='country',
            name='population',
            field=models.BigIntegerField(blank=True, null=True, verbose_name='Население'),
        ),
        migrations.AlterField(
            model_name='country',
            name='slug',
            field=models.SlugField(blank=True, unique=True, verbose_name='URL-адрес (slug)'),
        ),
        migrations.AlterField(
            model_name='datapoint',
            name='city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.city', verbose_name='Город'),
        ),
        migrations.AlterField(
            model_name='datapoint',
            name='country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.country', verbose_name='Страна'),
        ),
        migrations.AlterField(
            model_name='datapoint',
            name='indicator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.indicator', verbose_name='Показатель'),
        ),
        migrations.AlterField(
            model_name='datapoint',
            name='source',
            field=models.CharField(blank=True, max_length=150, verbose_name='Источник данных'),
        ),
        migrations.AlterField(
            model_name='datapoint',
            name='value',
            field=models.FloatField(verbose_name='Значение'),
        ),
        migrations.AlterField(
            model_name='datapoint',
            name='year',
            field=models.IntegerField(verbose_name='Год'),
        ),
        migrations.AlterField(
            model_name='indicator',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='indicators', to='main.indicatorcategory', verbose_name='Категория'),
        ),
        migrations.AlterField(
            model_name='indicator',
            name='code',
            field=models.CharField(help_text='Например: cost_of_living, safety_index', max_length=50, unique=True, verbose_name='Код показателя'),
        ),
        migrations.AlterField(
            model_name='indicator',
            name='global_max',
            field=models.FloatField(blank=True, help_text='Максимум для нормализации', null=True, verbose_name='Глобальный максимум'),
        ),
        migrations.AlterField(
            model_name='indicator',
            name='global_min',
            field=models.FloatField(blank=True, help_text='Минимум для нормализации', null=True, verbose_name='Глобальный минимум'),
        ),
        migrations.AlterField(
            model_name='indicator',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='indicator',
            name='unit',
            field=models.CharField(blank=True, max_length=30, verbose_name='Единицы измерения'),
        ),
        migrations.AlterField(
            model_name='indicatorcategory',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Название категории'),
        ),
        migrations.AlterField(
            model_name='indicatorcategory',
            name='slug',
            field=models.SlugField(unique=True, verbose_name='URL-адрес (slug)'),
        ),
        migrations.AlterField(
            model_name='modeindicatorweight',
            name='indicator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.indicator', verbose_name='Показатель'),
        ),
        migrations.AlterField(
            model_name='modeindicatorweight',
            name='mode',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weights', to='main.viewmode', verbose_name='Режим'),
        ),
        migrations.AlterField(
            model_name='modeindicatorweight',
            name='weight',
            field=models.FloatField(default=1.0, verbose_name='Вес (Множитель)'),
        ),
        migrations.AlterField(
            model_name='textinsight',
            name='city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.city', verbose_name='Город'),
        ),
        migrations.AlterField(
            model_name='textinsight',
            name='cons',
            field=models.JSONField(default=list, help_text='Пример:["Высокие налоги", "Дорогая аренда"]', verbose_name='Минусы (JSON список)'),
        ),
        migrations.AlterField(
            model_name='textinsight',
            name='country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.country', verbose_name='Страна'),
        ),
        migrations.AlterField(
            model_name='textinsight',
            name='mode',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.viewmode', verbose_name='Режим'),
        ),
        migrations.AlterField(
            model_name='textinsight',
            name='pros',
            field=models.JSONField(default=list, help_text='Пример: ["Теплый климат", "Виза D7"]', verbose_name='Плюсы (JSON список)'),
        ),
        migrations.AlterField(
            model_name='textinsight',
            name='summary',
            field=models.TextField(help_text='Основной текст-заключение', verbose_name='Короткий вывод'),
        ),
        migrations.AlterField(
            model_name='viewmode',
            name='description',
            field=models.TextField(blank=True, verbose_name='Описание режима'),
        ),
        migrations.AlterField(
            model_name='viewmode',
            name='name',
            field=models.CharField(max_length=50, unique=True, verbose_name='Название режима'),
        ),
        migrations.AlterField(
            model_name='viewmode',
            name='slug',
            field=models.SlugField(unique=True, verbose_name='URL-адрес (slug)'),
        ),
    ]
