# Generated by Django 5.2.10 on 2026-03-12 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_datapoint_options_alter_indicator_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='textinsight',
            name='cons',
        ),
        migrations.RemoveField(
            model_name='textinsight',
            name='pros',
        ),
        migrations.AlterField(
            model_name='textinsight',
            name='mode',
            field=models.CharField(choices=[('stats', 'Статистика'), ('relocation', 'Релокация'), ('tourism', 'Туризм')], max_length=20, verbose_name='Режим'),
        ),
    ]
