# Generated by Django 5.2.10 on 2026-03-12 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_remove_textinsight_cons_remove_textinsight_pros_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modeindicatorweight',
            name='mode',
            field=models.CharField(choices=[('stats', 'Статистика'), ('relocation', 'Релокация'), ('tourism', 'Туризм')], max_length=20, verbose_name='Режим'),
        ),
        migrations.AlterUniqueTogether(
            name='modeindicatorweight',
            unique_together={('mode', 'indicator')},
        ),
        migrations.AlterUniqueTogether(
            name='textinsight',
            unique_together={('country', 'city', 'mode')},
        ),
        migrations.DeleteModel(
            name='ViewMode',
        ),
    ]
