# Generated by Django 5.2.10 on 2026-03-12 18:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_modeindicatorweight_mode_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='datapoint',
            options={'verbose_name': 'Историческое значение', 'verbose_name_plural': 'Исторические значения'},
        ),
    ]
