# Generated by Django 5.2.10 on 2026-03-12 19:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_datapoint_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='datapoint',
            options={'verbose_name': 'Значение', 'verbose_name_plural': 'Значения'},
        ),
    ]
