# Generated by Django 5.2.10 on 2026-03-12 19:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_datapoint_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='textinsight',
            options={'verbose_name': 'Информация (страница)', 'verbose_name_plural': 'Информации (страницы)'},
        ),
    ]
