# Generated by Django 5.2.10 on 2026-03-19 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_alter_textinsight_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='country',
            name='flag_emoji',
        ),
        migrations.RemoveField(
            model_name='datapoint',
            name='source',
        ),
        migrations.AddField(
            model_name='datapoint',
            name='specific_source',
            field=models.CharField(blank=True, max_length=150, verbose_name='Специфический источник'),
        ),
        migrations.AddField(
            model_name='indicator',
            name='source',
            field=models.CharField(blank=True, max_length=150, verbose_name='Источник по умолчанию'),
        ),
        migrations.AlterField(
            model_name='country',
            name='iso_code',
            field=models.CharField(help_text="Используется для генерации флага (например: 'ru', 'us', 'kz')", max_length=2, unique=True, verbose_name='ISO Alpha-2 (Код)'),
        ),
        migrations.AlterField(
            model_name='indicator',
            name='code',
            field=models.CharField(max_length=50, unique=True, verbose_name='Код показателя'),
        ),
        migrations.AlterField(
            model_name='indicator',
            name='global_max',
            field=models.FloatField(blank=True, null=True, verbose_name='Глобальный максимум'),
        ),
        migrations.AlterField(
            model_name='indicator',
            name='global_min',
            field=models.FloatField(blank=True, null=True, verbose_name='Глобальный минимум'),
        ),
        migrations.AlterField(
            model_name='textinsight',
            name='summary',
            field=models.TextField(verbose_name='Короткий вывод'),
        ),
    ]
