# Generated by Django 5.2.10 on 2026-03-19 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_remove_country_flag_emoji_remove_datapoint_source_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='country',
            name='iso_code',
            field=models.CharField(help_text="Используется для генерации флага (например: 'ru', 'us', 'kz')", max_length=6, unique=True, verbose_name='ISO Alpha-2 (Код)'),
        ),
    ]
