# Generated by Django 5.2.10 on 2026-04-01 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_alter_country_iso_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='cities/', verbose_name='Фото обложки'),
        ),
        migrations.AddField(
            model_name='city',
            name='latitude',
            field=models.FloatField(blank=True, null=True, verbose_name='Широта (Lat)'),
        ),
        migrations.AddField(
            model_name='city',
            name='longitude',
            field=models.FloatField(blank=True, null=True, verbose_name='Долгота (Lon)'),
        ),
        migrations.AddField(
            model_name='city',
            name='name_ru',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Название (Рус - для сайта)'),
        ),
        migrations.AddField(
            model_name='city',
            name='osm_geojson',
            field=models.JSONField(blank=True, default=dict, verbose_name='GeoJSON (Точка/Границы для карты)'),
        ),
        migrations.AddField(
            model_name='country',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='countries/', verbose_name='Фото обложки'),
        ),
        migrations.AddField(
            model_name='country',
            name='latitude',
            field=models.FloatField(blank=True, null=True, verbose_name='Широта (Lat)'),
        ),
        migrations.AddField(
            model_name='country',
            name='longitude',
            field=models.FloatField(blank=True, null=True, verbose_name='Долгота (Lon)'),
        ),
        migrations.AddField(
            model_name='country',
            name='name_ru',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Название (Рус - для сайта)'),
        ),
        migrations.AddField(
            model_name='country',
            name='osm_geojson',
            field=models.JSONField(blank=True, default=dict, verbose_name='GeoJSON (Границы для OpenStreetMap)'),
        ),
        migrations.AlterField(
            model_name='city',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Название (Англ - для ссылок)'),
        ),
        migrations.AlterField(
            model_name='country',
            name='name',
            field=models.CharField(max_length=100, unique=True, verbose_name='Название (Англ - для ссылок)'),
        ),
    ]
