# Generated by Django 5.2.10 on 2026-04-01 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_city_image_city_latitude_city_longitude_city_name_ru_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='city',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='city',
            name='longitude',
        ),
        migrations.RemoveField(
            model_name='city',
            name='osm_geojson',
        ),
        migrations.RemoveField(
            model_name='country',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='country',
            name='longitude',
        ),
        migrations.RemoveField(
            model_name='country',
            name='osm_geojson',
        ),
        migrations.AlterField(
            model_name='city',
            name='is_capital',
            field=models.BooleanField(default=False, verbose_name='Столица?'),
        ),
        migrations.AlterField(
            model_name='city',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Название (Англ)'),
        ),
        migrations.AlterField(
            model_name='city',
            name='name_ru',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Название (Рус)'),
        ),
        migrations.AlterField(
            model_name='city',
            name='slug',
            field=models.SlugField(blank=True, verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='country',
            name='iso_code',
            field=models.CharField(max_length=6, unique=True, verbose_name='ISO Код'),
        ),
        migrations.AlterField(
            model_name='country',
            name='name',
            field=models.CharField(max_length=100, unique=True, verbose_name='Название (Англ)'),
        ),
        migrations.AlterField(
            model_name='country',
            name='name_ru',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Название (Рус)'),
        ),
        migrations.AlterField(
            model_name='country',
            name='slug',
            field=models.SlugField(blank=True, unique=True, verbose_name='Slug'),
        ),
    ]
