# Generated by Django 5.2.10 on 2026-04-01 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_remove_city_latitude_remove_city_longitude_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='latitude',
            field=models.FloatField(blank=True, null=True, verbose_name='Широта (Lat)'),
        ),
        migrations.AddField(
            model_name='city',
            name='longitude',
            field=models.FloatField(blank=True, null=True, verbose_name='Долгота (Lon)'),
        ),
        migrations.AddField(
            model_name='city',
            name='osm_geojson',
            field=models.JSONField(blank=True, default=dict, verbose_name='GeoJSON (Точка/Границы для карты)'),
        ),
        migrations.AddField(
            model_name='country',
            name='latitude',
            field=models.FloatField(blank=True, null=True, verbose_name='Широта (Lat)'),
        ),
        migrations.AddField(
            model_name='country',
            name='longitude',
            field=models.FloatField(blank=True, null=True, verbose_name='Долгота (Lon)'),
        ),
        migrations.AddField(
            model_name='country',
            name='osm_geojson',
            field=models.JSONField(blank=True, default=dict, verbose_name='GeoJSON (Границы для OpenStreetMap)'),
        ),
        migrations.AlterField(
            model_name='city',
            name='is_capital',
            field=models.BooleanField(default=False, verbose_name='Это столица?'),
        ),
        migrations.AlterField(
            model_name='city',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Название (Англ - для ссылок)'),
        ),
        migrations.AlterField(
            model_name='city',
            name='name_ru',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Название (Рус - для сайта)'),
        ),
        migrations.AlterField(
            model_name='city',
            name='slug',
            field=models.SlugField(blank=True, verbose_name='URL-адрес (slug)'),
        ),
        migrations.AlterField(
            model_name='country',
            name='iso_code',
            field=models.CharField(help_text="Используется для генерации флага (например: 'ru', 'us', 'kz')", max_length=6, unique=True, verbose_name='ISO Alpha-2 (Код)'),
        ),
        migrations.AlterField(
            model_name='country',
            name='name',
            field=models.CharField(max_length=100, unique=True, verbose_name='Название (Англ - для ссылок)'),
        ),
        migrations.AlterField(
            model_name='country',
            name='name_ru',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Название (Рус - для сайта)'),
        ),
        migrations.AlterField(
            model_name='country',
            name='slug',
            field=models.SlugField(blank=True, unique=True, verbose_name='URL-адрес (slug)'),
        ),
    ]
