# Generated by Django 5.2.10 on 2026-04-06 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_city_latitude_city_longitude_city_osm_geojson_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='textinsight',
            name='summary',
            field=models.TextField(max_length=200, verbose_name='Короткий вывод'),
        ),
    ]
