# Generated by Django 5.2.10 on 2026-04-10 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_alter_textinsight_summary'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='city',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='city',
            name='longitude',
        ),
        migrations.RemoveField(
            model_name='city',
            name='osm_geojson',
        ),
        migrations.RemoveField(
            model_name='country',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='country',
            name='longitude',
        ),
        migrations.RemoveField(
            model_name='country',
            name='osm_geojson',
        ),
        migrations.AlterField(
            model_name='city',
            name='latest_metrics',
            field=models.JSONField(blank=True, default=dict, verbose_name='Метрики по годам (gdp_ppp_2025, gdp_ppp_2026...)'),
        ),
    ]
